all:
  children:
    cloud:
      hosts:
        marton.cloud:
          ansible_host: marton.cloud
          ansible_user: marton
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    tailscale:
      hosts:
        ybuntu:
          ansible_host: ybuntu.neon-mermaid.ts.net
          ansible_user: marton
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_ssh_extra_args: '-o ProxyCommand="ssh -W %h:%p marton@marton.cloud"'

        raspberryy:
          ansible_host: raspberryy.neon-mermaid.ts.net
          ansible_user: pi
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_ssh_extra_args: '-o ProxyCommand="ssh -W %h:%p marton@marton.cloud"'

    local:
      hosts:
        zeropi:
          ansible_host: 192.168.50.80
          ansible_user: pi
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
          ansible_ssh_extra_args: '-o ProxyCommand="ssh -W %h:%p marton@ybuntu.neon-mermaid.ts.net"'
